export enum ERouteName {
  Today = 'Today',
  TodayCreateCourseScreen = 'TodayCreateCourseScreen',
  TodayEditCourseScreen = 'TodayEditCourseScreen',
  PurchaseScreen = 'PurchaseScreen',
  Summary = 'Summary',
  Log = 'Log',
  Settings = 'Settings',
  SettingsNotificationModal = 'SettingsNotificationModal',
  CourseTypeModal = 'CourseTypeModal',
  CourseDurationModal = 'CourseDurationModal',
  CourseOftennessModal = 'CourseOftennessModal',
  CourseTakeModal = 'CourseTakeModal',
  CourseSummaryModal = 'CourseSummaryModal',
}
