# Uncomment the next line to define a global platform for your project
platform :ios, "9.0"

target "laake" do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  #------- React core libs
  pod "DoubleConversion", :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod "glog", :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec"
  pod "Folly", :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod "React", :path => "../node_modules/react-native", :subspecs => [
                 "Core",
                 "CxxBridge",
                 "jsinspector",
                 "PrivateDatabase",
                 "cxxreact",
                 "ART",
                 "fishhook",
                 "DevSupport",
                 "RCTActionSheet",
                 "RCTAnimation",
                 "RCTGeolocation",
                 "RCTImage",
                 "RCTLinkingIOS",
                 "RCTNetwork",
                 "RCTSettings",
                 "RCTText",
                 "RCTVibration",
                 "RCTWebSocket",
                 "RCTPushNotification",
               ]
  #-------

  #

  # Pods for laake
  pod "Firebase/Core", "~> 5.20.1"
  pod "Firebase/Firestore", "~> 5.20.1"
  pod "Firebase/Messaging", "~> 5.20.1"
  pod "Firebase/Storage", "~> 5.20.1"
  pod "Firebase/Auth", "~> 5.20.1"
  pod "Firebase/Performance", "~> 5.20.1"
  pod "Firebase/AdMob", "~> 5.20.1"
  pod "RNFirebase", :path => "../node_modules/react-native-firebase/ios"

  pod "Fabric", "~> 1.7.13"
  pod "Crashlytics", "~> 3.10.7"

  pod "RNImageCropPicker", :path => "../node_modules/react-native-image-crop-picker"

  pod "RNGestureHandler", :path => "../node_modules/react-native-gesture-handler"

  pod "ReactNativePermissions", :path => "../node_modules/react-native-permissions"

  pod "react-native-haptic-feedback", :path => "../node_modules/react-native-haptic-feedback"

  pod "RNSVG", :path => "../node_modules/react-native-svg"

  pod "RNVectorIcons", :path => "../node_modules/react-native-vector-icons"

  pod "react-native-image-picker", :path => "../node_modules/react-native-image-picker"

  pod "RNIap", :path => "../node_modules/react-native-iap"
end
