# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'laake' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for laake
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Performance', '~> 5.20.1'

  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'

end