import { Animated } from 'react-native'

export const VARIABLES = {
  FONT_SIZE_GIANT: 32,
  FONT_SIZE_BIG: 24,
  FONT_SIZE_REGULAR: 18,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_TINY: 12,
  FONT_SIZE_NANO: 10,

  INPUT_HEIGHT: 62,
  INPUT_HEIGHT_SMALL: 48,
  BUTTON_HEIGHT: 48,

  PADDING_MEDIUM: 12,
  PADDING_BIG: 14,
  PADDING_SMALL: 6,

  DEFAULT_LOCALE: 'en',

  NULL_VALUE_SYMBOL: '–',

  CARD_WIDTH_MULTIPLIER: 0.8,

  START_NEW_COURSE_FROM_TIME_DEFAULT_VALUE: 8,
  START_NEW_COURSE_ACTIVE_DAY_HOURS: 16,

  BORDER_RADIUS_SMALL: 8,
  BORDER_RADIUS_BIG: 12,

  ANIMATED_VALUE_ZERO: new Animated.Value(0),
};
